import React, { useState } from 'react';

// ── Quality scoring data (moved from OverviewPage) ───────────────────────────
const SCORING_CRITERIA = [
  { label: 'Owner assigned',              points: 25, color: 'var(--fi-blue)',    icon: '👤', detail: 'A responsible person (subscription with type "responsible") is linked to the fact sheet.' },
  { label: 'Description present (>10 ch)', points: 15, color: 'var(--fi-success)', icon: '📝', detail: 'The description field contains more than 10 meaningful characters.' },
  { label: 'Lifecycle set (not EOL)',       points: 15, color: 'var(--fi-warning)', icon: '🔄', detail: 'A lifecycle phase is defined and it is not End of Life, Retired, or Decommissioned.' },
  { label: 'Completion ratio × 25',         points: 25, color: 'var(--gold)',       icon: '✅', detail: 'LeanIX completion ratio (0–1) multiplied by 25 gives 0–25 points. Reflects how many required fields are filled.' },
  { label: 'Updated < 90 days',             points: 20, color: 'var(--fi-success)', icon: '🕐', detail: 'Updated in last 90 days = +20 pts. Last 180 days = +10 pts. Last 365 days = +5 pts. Older = 0 pts.' },
];

const LOCKERS = [
  { id: 'bronze', label: 'Bronze', threshold: '< 45 pts',  color: 'var(--bronze)', bg: 'var(--bronze-bg)', border: 'var(--bronze-border)', desc: 'Incomplete data. Missing owner, lifecycle, stale, or description absent. Requires immediate attention from the fact sheet owner.' },
  { id: 'silver', label: 'Silver', threshold: '45 – 79 pts', color: 'var(--silver)', bg: 'var(--silver-bg)', border: 'var(--silver-border)', desc: 'Partial data. Basic fields present but needs enrichment: description detail, lifecycle confirmation, or staleness.' },
  { id: 'gold',   label: 'Gold',   threshold: '≥ 80 pts',   color: 'var(--gold)',   bg: 'var(--gold-bg)',   border: 'var(--gold-border)',   desc: 'Board-ready data. Fully enriched, owner assigned, lifecycle confirmed, updated recently. Suitable for architecture decisions.' },
];

const FAQ_ITEMS = [
  {
    q: 'Why does my vendor count differ from what I see in LeanIX?',
    a: 'ArchLens collects vendor names from three sources: Provider fact sheets, the vendors[] relationship on Application fact sheets, and vendors[] on ITComponent fact sheets. LeanIX only shows Provider fact sheet counts. ArchLens also deduplicates across all three sources, so the number may be lower or higher depending on how your data is structured.'
  },
  {
    q: 'What is the difference between Vendor Resolution and Vendor Analysis?',
    a: 'Vendor Analysis categorises raw vendor names into 16 business categories (ERP & Finance, Cloud Hosting, etc.) using AI. Vendor Resolution goes further: it deduplicates aliases and variants (SAP, SAP SE, SAP AG, S4HANA into one canonical entry) and builds a vendor-product-platform hierarchy. Always run Vendor Analysis before Vendor Resolution for best results.'
  },
  {
    q: 'How is the Bronze / Silver / Gold score calculated?',
    a: 'Each fact sheet is scored out of 100 points based on five criteria: owner assigned (+25), description present (+15), lifecycle set and not EOL (+15), LeanIX completion ratio × 25 (0–25), and recency of last update (+20/+10/+5/0). Bronze is below 45, Silver is 45–79, Gold is 80 or above. See the Quality Scoring section below for the full breakdown.'
  },
  {
    q: 'Can I use ArchLens without running a full sync first?',
    a: 'Some features require synced data. Connect (authentication) and Settings work immediately. The Vendor Analysis, Vendor Resolution, Duplicate Detection, Architecture AI, and all Intelligence features require at least a partial sync of Application and ITComponent fact sheets.'
  },
  {
    q: 'Why does the Architecture AI diagram sometimes show incomplete diagrams?',
    a: 'The Mermaid diagram is generated by the AI in a single token budget. For very complex architectures with many components, the diagram code can be truncated. If this happens, the page falls back to showing the raw Mermaid code which you can paste into mermaid.live to render. Reducing the scope of your requirement in the wizard typically resolves this.'
  },
  {
    q: 'How does Duplicate Detection work?',
    a: 'AI reads the name, description, tags, and vendor relationships of every Application, ITComponent, and Interface fact sheet and semantically clusters items by functional purpose, not just name similarity. Two apps called "PriceCalc-Legacy" and "PricingService-v3" would be clustered together if their descriptions and vendor context indicate they serve the same business function, even though their names differ.'
  },
  {
    q: 'What AI providers are supported?',
    a: 'ArchLens supports Anthropic Claude, OpenAI GPT-4o, Google Gemini 1.5 Pro, and DeepSeek. Configure your preferred provider and API key in Settings > AI Provider. Claude is recommended for the best analysis quality due to its larger context window and instruction-following capabilities. Gemini offers a generous free tier, making it a good starting point.'
  },
  {
    q: 'Does ArchLens store my LeanIX data on external servers?',
    a: 'No. ArchLens runs entirely on your own infrastructure (Node.js server + SQLite or your own DB). Your LeanIX data is fetched directly from the LeanIX GraphQL API and stored in your local database. The only external calls are to the AI API for analysis, and only the text content of fact sheet names and descriptions is sent, never credentials.'
  },
  {
    q: 'Can I schedule automatic syncs?',
    a: 'Yes. In Settings → Scheduler, you can create cron-based sync schedules (e.g. daily at 2am, weekly on Sunday). Each schedule can target specific fact sheet types. The scheduler runs server-side and persists across restarts.'
  },
  {
    q: 'What does the Modernization Analysis look at?',
    a: 'It reads every fact sheet of the selected type (Application, ITComponent, or Interface) and uses AI to identify modernization opportunities based on current technology trends. For interfaces it focuses on event-driven migration (Kafka, Azure Event Hub), API modernization (REST→GraphQL, AsyncAPI), and service mesh adoption. For applications it looks at cloud-native migration, SaaS replacement, and AI augmentation. For infrastructure it focuses on managed services, serverless, and FinOps optimisation.'
  },
];

const CONTACTS = [
  { role: 'General Support', email: 'vinodciandt@gmail.com', icon: '💬', desc: 'Bug reports, feature questions, and setup help' },
];

// ── Sub-page: FAQ + Quality Scoring ──────────────────────────────────────────
function FAQPage() {
  const [open, setOpen] = useState({});
  const toggle = i => setOpen(o => ({ ...o, [i]: !o[i] }));

  return (
    <div>
      {/* Quality Scoring card — moved from Overview */}
      <div className="fi-card" style={{ marginBottom: 28 }}>
        <div className="fi-card-header">
          <span className="fi-card-title">Quality Scoring: How Bronze / Silver / Gold is Determined</span>
        </div>
        <div className="fi-card-body">
          <p style={{ fontSize: 13, color: 'var(--fi-text-2)', lineHeight: 1.7, marginBottom: 20 }}>
            Every fact sheet in your LeanIX workspace is automatically scored out of <strong>100 points</strong> across
            five criteria. The score determines its data quality tier: Bronze, Silver, or Gold.
            Scores are recalculated on every sync.
          </p>

          {/* Scoring criteria */}
          <div style={{ marginBottom: 24 }}>
            <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--fi-text-2)', textTransform: 'uppercase', letterSpacing: '.05em', marginBottom: 12 }}>
              SCORING CRITERIA
            </div>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 0, border: '1px solid var(--fi-border)', borderRadius: 'var(--r)', overflow: 'hidden' }}>
              {SCORING_CRITERIA.map((c, i) => (
                <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 14, padding: '12px 16px', borderBottom: i < SCORING_CRITERIA.length - 1 ? '1px solid var(--fi-border)' : 'none', background: i % 2 === 0 ? 'var(--fi-page-bg)' : 'var(--fi-section-bg)' }}>
                  <span style={{ fontSize: 18, flexShrink: 0, marginTop: 1 }}>{c.icon}</span>
                  <div style={{ flex: 1 }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 3 }}>
                      <span style={{ fontWeight: 600, fontSize: 13, color: 'var(--fi-text)' }}>{c.label}</span>
                      <span style={{ fontFamily: 'var(--fm)', fontWeight: 800, fontSize: 14, color: c.color }}>+{c.points} pts</span>
                    </div>
                    <div style={{ fontSize: 12, color: 'var(--fi-text-3)', lineHeight: 1.5 }}>{c.detail}</div>
                  </div>
                  <div style={{ width: 40, flexShrink: 0 }}>
                    <div style={{ height: 4, borderRadius: 2, background: 'var(--fi-border)', overflow: 'hidden' }}>
                      <div style={{ height: '100%', width: `${c.points}%`, background: c.color, borderRadius: 2 }} />
                    </div>
                  </div>
                </div>
              ))}
              {/* Total row */}
              <div style={{ display: 'flex', justifyContent: 'flex-end', padding: '10px 16px', background: 'var(--fi-bg)', borderTop: '2px solid var(--fi-border)' }}>
                <span style={{ fontFamily: 'var(--fm)', fontWeight: 800, fontSize: 15, color: 'var(--fi-text)' }}>
                  Max: 100 pts
                </span>
              </div>
            </div>
          </div>

          {/* Tier thresholds */}
          <div>
            <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--fi-text-2)', textTransform: 'uppercase', letterSpacing: '.05em', marginBottom: 12 }}>
              QUALITY TIERS
            </div>
            <div className="grid-3" style={{ marginBottom: 16 }}>
              {LOCKERS.map(l => (
                <div key={l.id} style={{ padding: '14px 16px', borderRadius: 'var(--r2)', border: `1px solid ${l.border}`, background: l.bg }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                    <span style={{ fontWeight: 800, fontSize: 16, color: l.color }}>{l.label}</span>
                    <span style={{ fontFamily: 'var(--fm)', fontSize: 12, color: l.color, fontWeight: 700 }}>{l.threshold}</span>
                  </div>
                  <div style={{ fontSize: 12, color: 'var(--fi-text-2)', lineHeight: 1.6 }}>{l.desc}</div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* FAQ accordion */}
      <div style={{ fontSize: 15, fontWeight: 700, color: 'var(--fi-text)', marginBottom: 14 }}>Frequently Asked Questions</div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 0, border: '1px solid var(--fi-border)', borderRadius: 'var(--r2)', overflow: 'hidden' }}>
        {FAQ_ITEMS.map((item, i) => (
          <div key={i} style={{ borderBottom: i < FAQ_ITEMS.length - 1 ? '1px solid var(--fi-border)' : 'none' }}>
            <div onClick={() => toggle(i)} style={{
              display: 'flex', justifyContent: 'space-between', alignItems: 'center',
              padding: '14px 18px', cursor: 'pointer', background: open[i] ? 'var(--fi-blue-bg)' : 'var(--fi-page-bg)',
              transition: 'background .1s',
            }}>
              <span style={{ fontWeight: 600, fontSize: 13, color: open[i] ? 'var(--fi-blue)' : 'var(--fi-text)', lineHeight: 1.4, paddingRight: 16 }}>
                {item.q}
              </span>
              <span style={{ color: 'var(--fi-text-3)', flexShrink: 0, fontSize: 13, transform: open[i] ? 'rotate(90deg)' : 'none', transition: 'transform .15s' }}>▶</span>
            </div>
            {open[i] && (
              <div style={{ padding: '12px 18px 16px', background: 'var(--fi-section-bg)', fontSize: 13, color: 'var(--fi-text-2)', lineHeight: 1.7 }}>
                {item.a}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Sub-page: Contact Us ──────────────────────────────────────────────────────
function ContactPage() {
  return (
    <div>
      <div className="fi-msg info" style={{ marginBottom: 24 }}>
        <span>ℹ</span>
        <span>ArchLens is an open-source enterprise architecture intelligence platform. Community support is available via GitHub Issues.</span>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(260px,1fr))', gap: 16, marginBottom: 28 }}>
        {CONTACTS.map((c, i) => (
          <div key={i} className="fi-card">
            <div style={{ padding: '18px 20px' }}>
              <div style={{ fontSize: 28, marginBottom: 10 }}>{c.icon}</div>
              <div style={{ fontWeight: 700, fontSize: 14, marginBottom: 4 }}>{c.role}</div>
              <div style={{ fontSize: 12, color: 'var(--fi-text-3)', marginBottom: 12 }}>{c.desc}</div>
              <a href={`mailto:${c.email}`} style={{
                display: 'inline-flex', alignItems: 'center', gap: 6,
                fontSize: 13, color: 'var(--fi-blue)', fontWeight: 500,
              }}>✉ {c.email}</a>
            </div>
          </div>
        ))}
      </div>

      <div className="fi-card">
        <div className="fi-card-header">
          <span className="fi-card-title">GitHub &amp; Community</span>
          <div style={{ display:'flex', gap:10 }}>
            <a href="https://github.com/vinod-ea/archlens" target="_blank" rel="noreferrer"
              style={{ display:'inline-flex', alignItems:'center', gap:6, fontSize:12, fontWeight:600,
                color:'var(--fi-blue)', textDecoration:'none', padding:'4px 10px',
                border:'1px solid var(--fi-blue)', borderRadius:'var(--r)', lineHeight:1 }}>
              ★ GitHub Repository
            </a>
            <a href="https://github.com/vinod-ea" target="_blank" rel="noreferrer"
              style={{ display:'inline-flex', alignItems:'center', gap:6, fontSize:12, fontWeight:600,
                color:'var(--fi-text-2)', textDecoration:'none', padding:'4px 10px',
                border:'1px solid var(--fi-border)', borderRadius:'var(--r)', lineHeight:1 }}>
              👤 @vinod-ea
            </a>
          </div>
        </div>
        <div className="fi-card-body">
          <div className="grid-2">
            {[
              { icon: '🐛', label: 'Bug Reports',
                desc: 'Found something broken? Open an issue with steps to reproduce, your Node.js version, and browser console output.',
                href: 'https://github.com/vinod-ea/archlens/issues/new?template=bug_report.yml' },
              { icon: '💡', label: 'Feature Requests',
                desc: 'Have an idea for a new capability? Open a GitHub Discussion describing the use case and expected behaviour.',
                href: 'https://github.com/vinod-ea/archlens/issues/new?template=feature_request.yml' },
              { icon: '📖', label: 'Documentation',
                desc: 'Check the README in the repository for setup instructions, environment variables, and configuration reference.',
                href: 'https://github.com/vinod-ea/archlens#readme' },
              { icon: '🔧', label: 'Contributing',
                desc: 'Pull requests are welcome. See CONTRIBUTING.md for branch naming conventions and coding style guidelines.',
                href: 'https://github.com/vinod-ea/archlens/blob/main/CONTRIBUTING.md' },
            ].map((item, i) => (
              <a key={i} href={item.href} target="_blank" rel="noreferrer"
                style={{ display:'block', padding:'14px', background:'var(--fi-bg)', borderRadius:'var(--r)',
                  border:'1px solid var(--fi-border)', textDecoration:'none', transition:'border-color .15s' }}
                onMouseEnter={e=>e.currentTarget.style.borderColor='var(--fi-blue)'}
                onMouseLeave={e=>e.currentTarget.style.borderColor='var(--fi-border)'}>
                <div style={{ fontSize:22, marginBottom:8 }}>{item.icon}</div>
                <div style={{ fontWeight:600, fontSize:13, marginBottom:4, color:'var(--fi-text)' }}>{item.label}</div>
                <div style={{ fontSize:12, color:'var(--fi-text-3)', lineHeight:1.6 }}>{item.desc}</div>
              </a>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Sub-page: Terms & Conditions ──────────────────────────────────────────────
function TermsPage() {
  const sections = [
    { title: "1. Nature of the Software and Acceptance",
      body: "ArchLens (the Software) is an independent, open-source enterprise architecture intelligence tool distributed under the MIT License. By downloading, installing, configuring, or using the Software in any way, you (the User) accept these Terms in full. If you are acting on behalf of an organisation, you represent that you have authority to bind that organisation. These Terms apply to every version and release of ArchLens. If you do not accept these Terms, you must not use the Software." },
    { title: "2. MIT License and Intellectual Property",
      body: "ArchLens is distributed under the MIT License. You are granted a perpetual, worldwide, non-exclusive, royalty-free licence to use, copy, modify, merge, publish, distribute, sublicense, and sell copies of the Software, subject to inclusion of the original copyright notice in all copies. The name ArchLens, the ArchLens logo, and all associated branding remain the intellectual property of the original author(s). The MIT Licence does not grant any right to use those marks." },
    { title: "3. Independent Software: No Affiliation with Third-Party Vendors",
      body: "ArchLens is an independent open-source project. It is not developed, endorsed, sponsored, or approved by LeanIX GmbH, SAP SE, Ardoq AS, Anthropic PBC, OpenAI LP, Microsoft Corporation, or any other third-party organisation whose products or APIs the Software may interact with. All product names, logos, and brands referenced in the Software are the property of their respective owners and are used solely for identification and interoperability purposes. Such use does not imply any affiliation, partnership, or endorsement. ArchLens interacts with third-party APIs solely through credentials supplied by the User under that User\'s own subscription agreement with the respective vendor. ArchLens does not circumvent, reverse-engineer, or violate the terms of any third-party API or platform." },
    { title: "4. Data Processing and Storage",
      body: "ArchLens operates entirely on infrastructure owned and controlled by the User. All fact sheet data retrieved from the LeanIX API is stored exclusively in the User\'s locally configured database (SQLite, MySQL, or PostgreSQL) on the User\'s own server or machine. ArchLens does not operate any central server, cloud database, or data collection service. No organisational data, credentials, API keys, or fact sheet content is transmitted to the ArchLens project, its contributors, or any server operated by them. The User is solely responsible for the security, access control, backup, and data retention of all data stored by ArchLens on their infrastructure." },
    { title: "5. AI Provider Integration and Responsibility",
      body: "Certain features of ArchLens send fact sheet names, descriptions, and metadata to a third-party AI API (Anthropic Claude, OpenAI, or DeepSeek) configured and authenticated by the User using the User\'s own API key and account. By using AI features, the User acknowledges that: (a) data sent to AI APIs is processed under the terms and privacy policy of that third-party provider; (b) the User is solely responsible for ensuring such data transfers comply with their organisation\'s data governance policies and applicable law, including GDPR; (c) the User bears all costs associated with AI API usage; and (d) all AI-generated analysis is advisory only and must be independently validated by a qualified enterprise architect before any business decision is made based on it." },
    { title: "6. User Obligations and Acceptable Use",
      body: "The User agrees to: (a) use the Software only in compliance with all applicable laws and regulations; (b) use third-party APIs only in accordance with the User\'s own subscription agreements with those vendors; (c) not use the Software to gain unauthorised access to any system, network, or data; (d) not use the Software to process data for which the User does not have lawful authority; (e) not represent ArchLens as an official LeanIX, SAP, or other vendor product; and (f) not remove or obscure any copyright or attribution notices in the Software." },
    { title: "7. Disclaimer of Warranties",
      body: "THE SOFTWARE IS PROVIDED AS IS AND AS AVAILABLE, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. THE AUTHORS AND CONTRIBUTORS DO NOT WARRANT THAT THE SOFTWARE WILL OPERATE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT RESULTS OBTAINED FROM USE OF THE SOFTWARE WILL BE ACCURATE OR RELIABLE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE SOFTWARE IS WITH THE USER." },
    { title: "8. Limitation of Liability",
      body: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE AUTHORS, CONTRIBUTORS, OR COPYRIGHT HOLDERS OF ARCHLENS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL, OR PUNITIVE DAMAGES (INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, LOSS OF DATA, BUSINESS INTERRUPTION, OR LOSS OF GOODWILL) ARISING OUT OF OR RELATED TO THE USE OF OR INABILITY TO USE THE SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL THE TOTAL CUMULATIVE LIABILITY OF THE AUTHORS EXCEED ZERO EUROS, AS THE SOFTWARE IS PROVIDED FREE OF CHARGE." },
    { title: "9. Indemnification",
      body: "The User agrees to indemnify, defend, and hold harmless the authors, contributors, and maintainers of ArchLens from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees) arising out of or relating to: (a) the User\'s use of the Software; (b) the User\'s violation of these Terms; (c) the User\'s violation of any third-party right, including any intellectual property or privacy right; or (d) any claim that the User\'s use of the Software caused damage to a third party. This obligation survives termination of these Terms." },
    { title: "10. Third-Party Services",
      body: "The Software may connect to or reference third-party services (LeanIX, Anthropic, OpenAI, DeepSeek, and others). ArchLens has no control over and assumes no responsibility for the content, privacy policies, terms, uptime, or practices of any third-party service. Any use of third-party services is governed entirely by those services\' own terms. ArchLens does not receive any compensation from any third-party service mentioned or integrated into the Software." },
    { title: "11. Export Control and Sanctions Compliance",
      body: "The Software may be subject to export control laws and regulations in the User\'s jurisdiction. The User agrees to comply with all applicable export and import control laws. The User represents that they are not located in a country subject to applicable trade sanctions and are not listed on any government list of prohibited or restricted parties." },
    { title: "12. Governing Terms and Severability",
      body: "These Terms constitute the entire agreement between the User and the ArchLens authors regarding the subject matter hereof. If any provision is held to be unenforceable, it shall be modified to the minimum extent necessary to make it enforceable, and the remaining provisions shall continue in full force and effect. The failure to enforce any right or provision shall not constitute a waiver of that right." },
    { title: "13. Updates to These Terms",
      body: "These Terms may be revised from time to time. The current version is distributed with each ArchLens release and published in the project repository. Material changes will be noted in the release changelog. Continued use of the Software following publication of revised Terms constitutes acceptance of those revisions." },
  ];

  return (
    <div>
      <div style={{ marginBottom: 20, padding: '14px 18px', background: 'var(--fi-bg)', border: '1px solid var(--fi-border)', borderRadius: 'var(--r)', fontSize: 13, color: 'var(--fi-text-2)' }}>
        Last updated: March 2026 · ArchLens v3 · MIT License
      </div>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 0, border: '1px solid var(--fi-border)', borderRadius: 'var(--r2)', overflow: 'hidden' }}>
        {sections.map((s, i) => (
          <div key={i} style={{ padding: '16px 20px', borderBottom: i < sections.length - 1 ? '1px solid var(--fi-border)' : 'none', background: i % 2 === 0 ? 'var(--fi-page-bg)' : 'var(--fi-section-bg)' }}>
            <div style={{ fontWeight: 700, fontSize: 13, color: 'var(--fi-text)', marginBottom: 8 }}>{s.title}</div>
            <div style={{ fontSize: 13, color: 'var(--fi-text-2)', lineHeight: 1.7 }}>{s.body}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Main Support page with sub-navigation ────────────────────────────────────
const SUB_PAGES = [
  { id: 'faq',     label: 'FAQ',                    icon: '❓' },
  { id: 'contact', label: 'Contact Us',             icon: '✉'  },
  { id: 'terms',   label: 'Terms & Conditions',     icon: '📋' },
];

export default function SupportPage() {
  const [sub, setSub] = useState('faq');

  return (
    <div className="page-wrap mid fi-fade-in">
      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{ fontSize: 20, fontWeight: 700, marginBottom: 4 }}>Support</h1>
        <p style={{ fontSize: 13, color: 'var(--fi-text-2)' }}>
          Documentation, quality scoring reference, contact information and legal terms for ArchLens.
        </p>
      </div>

      {/* Sub-nav tabs */}
      <div style={{ display: 'flex', borderBottom: '1px solid var(--fi-border)', marginBottom: 24 }}>
        {SUB_PAGES.map(p => (
          <div key={p.id}
            className={`fi-nav-item${sub === p.id ? ' active' : ''}`}
            onClick={() => setSub(p.id)}
            style={{ fontSize: 13 }}>
            <span>{p.icon}</span>
            {p.label}
          </div>
        ))}
      </div>

      {/* Sub-page content */}
      <div className="fi-fade-in" key={sub}>
        {sub === 'faq'     && <FAQPage />}
        {sub === 'contact' && <ContactPage />}
        {sub === 'terms'   && <TermsPage />}
      </div>
    </div>
  );
}
